export default [
  {
    id: 1,
    title: 'Midnight Ember',
    price: '119.00',
    description:
      'A fresh and powerful fragrance with notes of bergamot, pepper, and amberwood. Perfect for the confident man.',
    category: 'men',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070981/',
    rating: { rate: 9.2, count: 320 },
    badge: 'Best Seller',
    shipping: 'Free Shipping',
  },
  {
    id: 2,
    title: 'Oceanic Noir',
    price: '135.00',
    description:
      'A woody aromatic fragrance with citrus, sandalwood, and cedar notes. Elegant and timeless.',
    category: 'men',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070982/',
    rating: { rate: 9.0, count: 280 },
    badge: '',
    shipping: 'Free Shipping',
  },
  {
    id: 3,
    title: 'Aqua Mystique',
    price: '125.00',
    description:
      'A sophisticated aquatic fragrance with bergamot, patchouli, and incense notes.',
    category: 'men',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070983/',
    rating: { rate: 8.8, count: 450 },
    badge: '',
    shipping: '',
  },
  {
    id: 4,
    title: 'Nocturnal Spice',
    price: '98.00',
    description:
      'Spicy cardamom blends with cedarwood and coumarin for a sensual night-time scent.',
    category: 'men',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070984/',
    rating: { rate: 8.7, count: 390 },
    badge: 'Low Stock',
    shipping: '',
  },
  {
    id: 5,
    title: 'Crimson Aura',
    price: '145.00',
    description:
      'A bold feminine fragrance with orange, jasmine, and rose, balanced by patchouli and vetiver.',
    category: 'women',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070985/',
    rating: { rate: 9.5, count: 510 },
    badge: 'Top Rated',
    shipping: 'Free Shipping',
  },
  {
    id: 6,
    title: 'Eternal Blossom',
    price: '120.00',
    description:
      'Sweet and floral with iris, praline, and vanilla — a modern classic for women.',
    category: 'women',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070986/',
    rating: { rate: 9.1, count: 420 },
    badge: '',
    shipping: 'Free Shipping',
  },
  {
    id: 7,
    title: 'Floral Reverie',
    price: '130.00',
    description:
      'A rich white floral fragrance with jasmine, tuberose, and Rangoon creeper.',
    category: 'women',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070987/',
    rating: { rate: 8.9, count: 380 },
    badge: '',
    shipping: '',
  },
  {
    id: 8,
    title: 'Wild Petal',
    price: '110.00',
    description:
      'Playful and fresh with notes of wild strawberry, violet leaves, and jasmine.',
    category: 'women',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070988/',
    rating: { rate: 8.6, count: 350 },
    badge: '',
    shipping: '',
  },
  {
    id: 9,
    title: 'Golden Oud',
    price: '250.00',
    description:
      'Exotic and rich, blending rare oud wood with cardamom, sandalwood, and tonka bean.',
    category: 'men',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070989/',
    rating: { rate: 9.4, count: 210 },
    badge: 'Luxury',
    shipping: 'Free Shipping',
  },
  {
    id: 10,
    title: 'Silver Mirage',
    price: '105.00',
    description:
      'Warm and spicy with blood mandarin, cinnamon, and leather notes — bold and masculine.',
    category: 'men',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070990/',
    rating: { rate: 8.7, count: 500 },
    badge: 'Popular',
    shipping: '',
  },
  {
    id: 11,
    title: 'Verdant Essence',
    price: '118.00',
    description:
      'Fresh mint, green apple, and vanilla create a vibrant and passionate men’s fragrance.',
    category: 'men',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070991/',
    rating: { rate: 8.9, count: 370 },
    badge: '',
    shipping: '',
  },
  {
    id: 12,
    title: 'Royal Legacy',
    price: '350.00',
    description:
      'Iconic and powerful with pineapple, birch, and oakmoss — a statement fragrance for men.',
    category: 'men',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070992/',
    rating: { rate: 9.7, count: 600 },
    badge: 'Premium',
    shipping: 'Free Shipping',
  },
  {
    id: 13,
    title: 'Timeless Charm',
    price: '99.00',
    description:
      'Mint, lavender, and vanilla combine in this iconic masculine fragrance.',
    category: 'men',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070993/',
    rating: { rate: 8.8, count: 460 },
    badge: '',
    shipping: '',
  },
  {
    id: 14,
    title: 'Celestial Path',
    price: '125.00',
    description:
      'Bright and floral with orange blossom, tuberose, and vanilla — a scent for the curious soul.',
    category: 'women',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070994/',
    rating: { rate: 9.0, count: 310 },
    badge: '',
    shipping: 'Free Shipping',
  },
  {
    id: 15,
    title: 'Midnight Bloom',
    price: '140.00',
    description:
      'A seductive blend of coffee, vanilla, and white flowers for the modern woman.',
    category: 'women',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070995/',
    rating: { rate: 9.3, count: 550 },
    badge: 'Hot Item',
    shipping: '',
  },
  {
    id: 16,
    title: 'Wanderlust Essence',
    price: '196.00',
    description:
      'Woody and aromatic with juniper berries, lemon, and sandalwood for a free-spirited vibe.',
    category: 'women',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070996/',
    rating: { rate: 8.9, count: 260 },
    badge: '',
    shipping: 'Free Shipping',
  },
  {
    id: 17,
    title: 'Velvet Whisper',
    price: '145.00',
    description:
      'A floral and fruity scent with peony, red apple, and suede — soft yet confident.',
    category: 'women',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070997/',
    rating: { rate: 8.7, count: 230 },
    badge: '',
    shipping: '',
  },
  {
    id: 18,
    title: 'Enchanted Veil',
    price: '130.00',
    description:
      'Elegant with orange blossom, jasmine, and vetiver — a daringly feminine fragrance.',
    category: 'women',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070998/',
    rating: { rate: 9.1, count: 410 },
    badge: '',
    shipping: 'Free Shipping',
  },
  {
    id: 19,
    title: 'Earthbound Spirit',
    price: '125.00',
    description:
      'Earthy and citrusy with orange, pepper, and vetiver for the grounded gentleman.',
    category: 'men',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1070999/',
    rating: { rate: 9.0, count: 390 },
    badge: '',
    shipping: '',
  },
  {
    id: 20,
    title: 'Mystic Aura',
    price: '120.00',
    description:
      'Mystical and radiant with jasmine, cashmere wood, and amber.',
    category: 'women',
    image: 'https://www.pexels.com/photo/clear-glass-perfume-bottle-1071000/',
    rating: { rate: 9.2, count: 470 },
    badge: 'Get 10% OFF^',
    shipping: '',
  },
];
